plugin {
  touch_gestures {
	  hyprgrass-bind = ,wipe:3:u,exec, notify-send '123'  
  }

  overview {
    panelColor = rgba(11111bcc)
    panelBorderColor = rgba(89b4faff)
    panelHeight = 180
    panelBorderWidth = 2
    onBottom = false
    reservedArea = 0

    workspaceActiveBackground = rgba(313244ee)
    workspaceInactiveBackground = rgba(1e1e2ecc)
    workspaceActiveBorder = rgba(a6e3a1ff)
    workspaceInactiveBorder = rgba(45475aff)
    workspaceMargin = 10
    workspaceBorderSize = 2
    centerAligned = true

    exitOnClick = true
    exitOnSwitch = true
    switchOnDrop = true
    showNewWorkspace = true
    showEmptyWorkspace = true
    showSpecialWorkspace = false
    exitKey = Escape
  }

  hyprexpo {
      columns = 3
      gaps_in = 5
      gaps_out = 0
      bg_col = rgb(111111)
      workspace_method = center current
      gesture_distance = 200
      cancel_key = escape
      show_cursor = 1
      show_pinned_windows = 0
  }
  
  hyprbars{
    # example config
    bar_height = 20
    # example buttons (R -> L)
    # hyprbars-button = color, size, on-click
    hyprbars-button = rgb(ff4040), 10, 󰖭, hyprctl dispatch killactive
    hyprbars-button = rgb(eeee11), 10, , hyprctl dispatch fullscreen 1

    }
    hyprcapture {
      default_mode = region
      fullscreen_scope = all
      window_background = follow-system
      window_border = keep
      window_shadow = keep
      save = 1
      clipboard = 1
      show_thumbnail = 1
      allow_quick = 0
      confirm_before_capture = 0
      fusion_mode = 0
      save_dir = ~/Pictures/ScreenShots
      filename_template = Screenshot-%Y-%m-%d-%H%M%S.png
      record_save_dir = $XDG_VIDEOS_DIR/Screenrecords
      record_filename_template = Recording-%Y-%m-%d-%H%M%S.mp4
      record_format = mp4
      record_transparent_format = webm
      record_fps = 30
      record_fps_options = 15 24 30 60
      record_window_fps_limit = 12
      record_window_real_bg_fps_limit = 8
      record_codec = libx264
      record_transparent_codec = auto
      record_solid_alpha = 0
      record_preset = veryfast
      record_gsr_flags =
      record_window_backend = compositor
      record_max_seconds = 0
      record_countdown_seconds = 0
      include_cursor = 0
      thumbnail_timeout_ms = 5000
      watermark =
      watermark_position = central
      watermark_width = 20%
      watermark_offset = 0 0
  }
}
