import os
import subprocess
from pathlib import Path

# ===== DEBUG Setting =====
DEBUG = False

config_file = '/home/tomato/.config/waybar/waybar_theme_config'
css_file = "/home/tomato/.config/waybar/customcolors.css"

COLOR_SCHEMES = {
    "dark": {
        "bg_color": "#1e1e2e",
        "text_color": "#cdd6f4",
        "accent_color": "#89b4fa",
        "urgent_color": "#f38ba8",
        "hover_color": "#585b70",
        "volume_color": "#f5c2e7",
        "brightness_color": "#f9e2af",
        "battery_color": "#a6e3a1",
        "clock_color": "#89b4fa",
        "music_color": "#cba6f7",
        "lock_color": "#b4befe",
        "power_color": "#f38ba8"
    },
    "light": {
        "bg_color": "#f5f5fa",
        "text_color": "#4c4f69",
        "accent_color": "#1e66f5",
        "urgent_color": "#d20f39",
        "hover_color": "#ccd0da",
        "volume_color": "#ea76cb",
        "brightness_color": "#df8e1d",
        "battery_color": "#40a02b",
        "clock_color": "#1e66f5",
        "music_color": "#8839ef",
        "lock_color": "#7287fd",
        "power_color": "#d20f39"
    }
}


# ===== 统一日志 =====
def log(msg):
    if not DEBUG:
        return

    print(msg)

    try:
        subprocess.run([
            "notify-send",
            "Theme Switcher",
            str(msg)
        ], check=False)
    except Exception:
        pass


def run(cmd):
    subprocess.run(cmd, check=False)


def get_current_theme():
    if os.path.exists(config_file):
        with open(config_file, 'r') as f:
            theme = f.read().strip()
            if theme in COLOR_SCHEMES:
                return theme

    Path(config_file).parent.mkdir(parents=True, exist_ok=True)
    with open(config_file, 'w') as f:
        f.write('dark')
    return 'dark'


def get_next_theme(current_theme):
    return "light" if current_theme == "dark" else "dark"


def update_waybar_colors(theme):
    colors = COLOR_SCHEMES[theme]

    css_content = f"""/* Auto-generated by waybar theme switcher */
@define-color bg_color {colors["bg_color"]};
@define-color text_color {colors["text_color"]};
@define-color accent_color {colors["accent_color"]};
@define-color urgent_color {colors["urgent_color"]};
@define-color hover_color {colors["hover_color"]};
@define-color volume_color {colors["volume_color"]};
@define-color brightness_color {colors["brightness_color"]};
@define-color battery_color {colors["battery_color"]};
@define-color clock_color {colors["clock_color"]};
@define-color music_color {colors["music_color"]};
@define-color lock_color {colors["lock_color"]};
@define-color power_color {colors["power_color"]};
"""

    Path(css_file).parent.mkdir(parents=True, exist_ok=True)

    with open(css_file, 'w') as f:
        f.write(css_content)

    log(f"Waybar → {theme}")


def update_gtk_theme(theme):
    if theme == "dark":
        gtk_theme = "Adwaita-dark"
        color_scheme = "prefer-dark"
    else:
        gtk_theme = "Adwaita"
        color_scheme = "prefer-light"

    run([
        "gsettings",
        "set",
        "org.gnome.desktop.interface",
        "gtk-theme",
        gtk_theme
    ])

    run([
        "gsettings",
        "set",
        "org.gnome.desktop.interface",
        "color-scheme",
        color_scheme
    ])

    log(f"GTK → {gtk_theme}")
    log(f"Color-scheme → {color_scheme}")


def restart_waybar():
    run(["killall", "-SIGUSR2", "waybar"])
    log("Waybar restarted")


def save_theme(theme):
    with open(config_file, 'w') as f:
        f.write(theme)
    log(f"Saved theme: {theme}")


def main():
    try:
        current_theme = get_current_theme()
        new_theme = get_next_theme(current_theme)

        log(f"当前: {current_theme}")
        log(f"切换到: {new_theme}")

        update_waybar_colors(new_theme)
        update_gtk_theme(new_theme)
        save_theme(new_theme)
        restart_waybar()

    except Exception as e:
        log(f"Error: {e}")
        exit(1)


if __name__ == "__main__":
    main()