#windowrule = float,^(floating_terminal)$
#windowrule = plugin:hyprbars:nobar, tag:no_titlebar

#windowrulev2 = noblur, class:^(Microsoft-edge)$
#windowrulev2 = noshadow, class:^(Microsoft-edge)$

# windowrulev2 = float, class:^(picgo)$
# #windowrulev2 = pin, class:^(picgo)$
# windowrulev2 = move 93% 5%, class:^(picgo)$
# windowrulev2 = opacity 0.6, class:^(picgo)$

# swaync notifications blur (frosted glass)
layerrule {
  name = swaync-blur
  blur = on
  ignore_alpha = 0.5
  match:namespace = notifications
}

# rofi blur
layerrule {
  name = rofi-blur
  blur = on
  ignore_alpha = 0
  match:namespace = rofi
}
